# Generated by Django 3.0.1 on 2019-12-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191227_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alisubmission',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='alisubmission',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='alisubmission',
            old_name='product',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='alisubmission',
            old_name='rating',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='alisubmission',
            old_name='search',
            new_name='Search',
        ),
        migrations.RenameField(
            model_name='alisubmission',
            old_name='shipping',
            new_name='Shipping',
        ),
        migrations.RenameField(
            model_name='alisubmission',
            old_name='sold',
            new_name='Sold',
        ),
        migrations.AddField(
            model_name='alisubmission',
            name='User',
            field=models.CharField(default='Ghost user...', max_length=250),
        ),
    ]
