# Generated by Django 3.0.1 on 2019-12-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191229_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alisubmission',
            name='Price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alisubmission',
            name='Product',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alisubmission',
            name='Rating',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alisubmission',
            name='Shipping',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alisubmission',
            name='Sold',
            field=models.TextField(),
        ),
    ]
