# Generated by Django 3.0.1 on 2019-12-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191229_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alisubmission',
            old_name='Price',
            new_name='Prices',
        ),
        migrations.RenameField(
            model_name='alisubmission',
            old_name='Product',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='alisubmission',
            old_name='Rating',
            new_name='Ratings',
        ),
        migrations.AddField(
            model_name='alisubmission',
            name='Suppliers',
            field=models.TextField(default='N/A'),
        ),
    ]
